# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Versión de sintaxis de Vagrantfile. No toques, a menos que se sepas lo que estás haciendo.
VERSION = "2"
 
# Configuración de la maquina virtual.
Vagrant.configure(VERSION) do |config|

  # Configuración mínima del sistema. (https://www.vagrantup.com/docs/virtualbox/configuration.html)
  config.vm.provider "virtualbox" do |v|
  	v.name = "Ubuntu.Server"
    v.memory = 1024
    v.cpus = 1
  end

  # Caja (Por defecto: Ubuntu 14.04).
  config.vm.box = "ubuntu/trusty64"
  # Redireccionamiento de puertos.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # IP privada.
  config.vm.network "private_network", ip: "192.168.33.10"
  # Carpeta compartida.
  config.vm.synced_folder "./", "/var/www/html"
  # Archivo para la instalación y configuración del entorno de desarrollo.
  config.vm.provision "shell", path: "config.sh"

end
