# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
# Version de sintaxis de Vagrantfile. No tocar, a menos que se sepa lo que se esta haciendo.
VAGRANTFILE_API_VERSION = "2"
 
# Configuracion de la maquina virtual.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"								# Caja (Por defecto: Ubuntu 14.04)
  config.vm.network "forwarded_port", guest: 80, host: 8080		# Redireccionamiento de puertos
  config.vm.network "private_network", ip: "192.168.33.10"		# IP privada
  config.vm.synced_folder "./", "/var/www/html"					# Carpeta compartida
  config.vm.provision "shell", path: "config.sh"				# Archivo para la instalacion y configuracion del entorno de desarrollo

end